---

name: MegaLinter

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    name: MegaLinter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: MegaLinter
        uses: megalinter/megalinter/flavors/terraform@v5
        env:
          VALIDATE_ALL_CODEBASE: ${{ github.event_name == 'workflow_dispatch' }}
          GITHUB_TOKEN: "${{ steps.generate-token.outputs.token }}"
          ENABLE_LINTERS: >-
            ACTION_ACTIONLINT,
            BASH_SHELLCHECK,
            DOCKERFILE_HADOLINT,
            ENV_DOTENV_LINTER,
            GIT_GIT_DIFF,
            MARKDOWN_MARKDOWNLINT,
            YAML_YAMLLINT
          MARKDOWN_MARKDOWNLINT_CONFIG_FILE: .markdownlint.yaml
          YAML_YAMLLINT_CONFIG_FILE: .yamllint.yaml
      - name: Archive production artifacts
        if: ${{ success() }} || ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: MegaLinter reports
          path: |
            report
            mega-linter.log
